AWSTemplateFormatVersion: "2010-09-09"
Description: Create an S3 Bucket for Portfolio

Resources:
  Bucket:
    Type: AWS::S3::Bucket

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/*"

Outputs:
  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref Bucket