AWSTemplateFormatVersion: "2010-09-09"
Description: Create an S3 Bucket for Portfolio

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gajinkim.com
      WebsiteConfiguration:
        IndexDocument: "index.html"
        # ErrorDocument: 'index.html'
      Tags:
        - Key: Name
          Value: gajinkim.com

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/*"
            Principal: "*"
            Sid: "PublicReadGetObject"

  # RecordSet:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     Name: gajinkim.com
  #     HostedZoneId: Z00684801I7GELBGWLUZY
  #     AliasTarget:
  #       DNSName: s3-website.us-east-1.amazonaws.com
  #       HostedZoneId: Z3AQBSTGFYJSTF
  #     Type: A

  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z00684801I7GELBGWLUZY
      RecordSets:
        - Name: gajinkim.com.
          Type: A
          AliasTarget:
            HostedZoneId: Z3AQBSTGFYJSTF
            DNSName: s3-website.us-east-1.amazonaws.com

Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref Bucket
