AWSTemplateFormatVersion: "2010-09-09"
Description: Create an S3 Bucket for Portfolio

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Name
          Value: gajinkim.com

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/*"
            Principal: '*'

Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref Bucket