AWSTemplateFormatVersion: "2010-09-09"
Description: Create an S3 Bucket for Portfolio

Resources:
  Bucket:
    Type: AWS::S3::Bucket

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket

Outputs:
  Bucketname:
    Description: S3 Bucket Name
    Value: !Ref Bucket