name: ci-prod

on:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read
  deployments: write

env:
  REGION: us-east-1

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    env:
      STACK_NAME: portfolio-cloudformation-stack
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ARN_AWS_IAM_ROLE }}
          aws-region: ${{ env.REGION }}

      - name: Deploy ${{ env.STACK_NAME }}
        run: |
          sam deploy --stack-name $STACK_NAME --region $REGION

      - name: Deploy S3 Bucket
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' --output text)
          aws s3 cp src s3://$BUCKET_NAME --recursive
